CT-12 /CT-59
connectattoo/connectattoo.backend pull request #15
Opened 2024-01-31 14:56 UTC by lucas6g

- adicionado novo template de confirmação de email 
- adicionado novas configurações de envio de email

2024-01-31 15:23 UTC, erickmarx requested changes
Evite utilizar bibliotecas frontend no backend.

Ao invés de utilizar React para fazer o template de email, utilize o pacote Handlebars.js

O proposito deste pacote é criar templates HTML para serem utilizados dentro da aplicação.

https://www.npmjs.com/package/handlebars
https://handlebarsjs.com/
https://www.treinaweb.com.br/blog/nestjs-com-template-engine-handlebars

2024-02-16 02:30 UTC, erickmarx commented on src/shared/adapters/mail/mail.module.ts
> +      preview: true,
Creio que esqueceu de remover isto, imagino que não seja necessario para o disparo do template.

2024-02-16 02:33 UTC, erickmarx commented on tsconfig.json
> +    "jsx": "react-jsx",
Isto é necessario?

2024-02-16 02:34 UTC, erickmarx requested changes, later dismissed
Faz o pull de origin/develop para está branch por que houve alterações em um dos arquivos que voce trabalhou

2024-02-17 01:52 UTC, lucas6g commented on tsconfig.json
> +    "jsx": "react-jsx",
sim

2024-02-17 13:40 UTC, erickmarx commented on .gitmodules
> +[submodule "@connectattoo/email-templates"]
Não conheço muito sobre submodule do git, mas não deveria apontar a branch em algum lugar? ou está implicito que será usado a branch main?

2024-02-17 13:51 UTC, natanaelsc commented on .gitmodules
> +[submodule "@connectattoo/email-templates"]
Eu também não conheço muito, mas pelo que eu vi sobre não era necessário. Talvez seja, talvez não.

2024-02-17 16:20 UTC, erickmarx commented on .gitmodules
> +[submodule "@connectattoo/email-templates"]
achei isso, talvez ajude.

https://stackoverflow.com/questions/1777854/how-can-i-specify-a-branch-tag-when-adding-a-git-submodule

2024-02-17 19:01 UTC, natanaelsc commented on .gitmodules
> +[submodule "@connectattoo/email-templates"]
Boa, muito útil!

2024-02-18 23:07 UTC, natanaelsc approved these changes

2024-02-18 23:10 UTC, merged