add tag seeds
connectattoo/connectattoo.backend pull request #18
Opened 2024-04-10 22:31 UTC by erickmarx

2024-04-10 23:56 UTC, natanaelsc commented on Dockerfile
> +CMD ["/bin/sh", "-c", "npx prisma migrate deploy;node prisma/seed.js;node dist/main.js"]
É retornado `Error: Cannot find module '/api/prisma/seed.js'` ao executar essa linha com `docker compose up`.
O arquivo seed não está na pasta prisma quando compilado. Ele está em `dist/shared/adapters/prisma/seeds/index.js`.
O comando ficaria `CMD ["/bin/sh", "-c", "npx prisma migrate deploy;node dist/shared/adapters/prisma/seeds/index.js;node dist/main.js"]
`

2024-04-11 00:01 UTC, natanaelsc requested changes
* Adicionar o caminho correto do arquivo de seed no Dockerfile linha 31
* Adicionar a execução do seed ao arquivo `entrypoint.sh` na pasta `.docker`

2024-04-11 21:43 UTC, natanaelsc commented on .docker/entrypoint.sh
Esse entrypoint é para o build de desenvolvimento, era somente para adicionar a linha para executar o seed

2024-04-11 21:43 UTC, natanaelsc commented on .docker/entrypoint.sh
> +npm run start
Não para ter alterado

2024-04-11 21:44 UTC, natanaelsc commented on .docker/entrypoint.sh
> -npx prisma migrate dev
Não era para ser alterado

2024-04-11 22:37 UTC, erickmarx commented on .docker/entrypoint.sh
> -npx prisma migrate dev
migrate dev gera uma nova migration caso haja divergencia entre o prisma schema e o prisma migrations, o migrate deploy apenas aplica as migrations no postgres.

o proposito deste migrate dev é criar novas migrations na geração do build da aplicação? 🤔

2024-04-11 22:38 UTC, erickmarx commented on .docker/entrypoint.sh
> +npm run start
é necessario que a aplicação fique seja buildado em watch mode, mesmo que em caso de erro de builds, o container crashe? 🤔

2024-04-11 23:32 UTC, natanaelsc commented on .docker/entrypoint.sh
> +npm run start
Sim

2024-04-11 23:35 UTC, natanaelsc commented on .docker/entrypoint.sh
> -npx prisma migrate dev
Esse é um ambiente de desenvolvimento

2024-04-12 21:42 UTC, erickmarx commented on .docker/entrypoint.sh
> +npm run start
poderia me explicar por que?

2024-04-12 21:43 UTC, erickmarx commented on .docker/entrypoint.sh
> -npx prisma migrate dev
sim, estou ciente.
mas a funcionalidade não bate com a proposta da solução.

2024-04-14 23:29 UTC, natanaelsc approved these changes

2024-04-14 23:29 UTC, merged