CT-22/CT-128
connectattoo/connectattoo.backend pull request #39
Opened 2024-04-30 01:39 UTC by RafaelRtx

- Adicionado método para buscar informações do usuário através do user Id em User Repository
- Adicionado o email do usuário ao objeto de resposta da rota profile/me

2024-04-30 01:53 UTC, erickmarx requested changes
Quanto menos injeções fizer em uma service, menor a chance de criar dependencia ciclica (profileModule injeta userModule e userModule injeta profileModule).

Com essa conceito em mente, pense em como conseguir a propriedade email através do profileRepository.

2024-04-30 15:26 UTC, erickmarx requested changes

2024-04-30 15:26 UTC, erickmarx commented on src/modules/profile/profile.repository.ts
> +  async getUserByUserId(userId: string): Promise<Nullable<User>> {
Faz sentido profileRepository ter acesso a tabela User?

2024-04-30 16:21 UTC, erickmarx requested changes

2024-04-30 16:21 UTC, erickmarx commented on src/modules/profile/profile.repository.ts
> +  async getUserByUserId(userId: string): Promise<Nullable<User>> {
O que acha da possibilidade de haver um metodo chamado: getProfileAndUser?

2024-05-03 15:46 UTC, erickmarx requested changes

2024-05-03 15:46 UTC, erickmarx commented on src/modules/profile/interface/me.interface.ts
> +  email: string | null;
Sempre haverá email, então ele nunca vai ser null

2024-05-03 15:46 UTC, erickmarx commented on src/modules/profile/interface/get-profile-with-user-email.ts
> +export type getProfileAndUserEmailType = Nullable<
essa interface pode servir pra mais coisas, um nome mais apropriado seria `getProfileAndUserType`. Não esquece do nome do arquivo

2024-05-03 15:46 UTC, erickmarx commented on src/modules/profile/interface/get-profile-with-user-email.ts
> +  Profile & { user: Nullable<User> }
Tire o Nullable para fazer com que o user não possa mais ser null, e caso o typescript ainda continue reclamando, experimente fazer uma validação com if

2024-05-05 12:54 UTC, natanaelsc approved these changes

2024-05-05 12:55 UTC, merged