CT-32/CT-144
connectattoo/connectattoo.backend pull request #48
Opened 2024-05-29 02:53 UTC by RafaelRtx

- Adicionado patch-profile DTO para validação
- Adicionada patch-profile interface para o método PATCH na rota profile/me
- Adicionada funcionalidade do usuário alterar os dados de perfil name, username, email ou birthDate usando o método http PATCH na rota profile/me

2024-05-31 18:24 UTC, erickmarx requested changes
Na função patchMe na service, não é necessario fazer a desestruturação e reestruturação do objeto validado vindo da controller, da mesma forma que é redundante validar cada valor vindo do body, sendo possivel dar essa responsabilidade ao prisma/relacional.

Se houver duvidas sobre o que foi apontado aqui, pode me chamar no discord, vai ser um prazer te ajudar a melhorar.

2024-05-31 18:24 UTC, erickmarx commented on src/modules/profile/interface/update-profile.interface.ts
> +  name: string;
Essa alteração estava previsto na task? caso não, tem que tomar cuidado por que isso reflete mais do que apenas no backend, o mobile precisa saber que a propriedade `displayName` foi alterado para `name`, o que causa uma dependência técnica para eles.

2024-05-31 18:24 UTC, erickmarx commented on src/modules/profile/profile.repository.ts
> +    return await this.prismaService.profile.findMany({
O nome da função indica um unico profile, e por que não utilizar `findFirst` para pegar apenas o perfil que usa username ou email? o schema do garantirá que existe apenas um usuario.

2024-05-31 18:24 UTC, erickmarx commented on src/modules/profile/profile.service.ts
> +    const body = {
O que acontece no caso de um propriedade estiver `undefined`? 

Por exemplo, `username`, a função buscará no repository por registros em que `username` é `undefined`, que nunca vai existir garantido pelo schema do prisma, resultando em Internal Server Error.

Para resolver isso, basta não desestructurar e estruturar de novo, confie no objeto vindo do controller.

2024-05-31 18:24 UTC, erickmarx commented on src/modules/profile/profile.service.ts
> +    { name, username, email, birthDate }: IPatchProfile,
Você utilizou DTO com class-validator para validação e atribuição de variaveis, aqui voce fez outra validação abrindo espaço para valores indefinidos.

Não há necessidade de desestruturar, confie na variavel que vem do controller, ele foi validado pelo class-validator.

2024-05-31 18:24 UTC, erickmarx commented on src/modules/profile/profile.service.ts
> +    profileData.map(async (profile) => {
estas validações não são necessarias no caso de repository retornar um unico valor e class-validator já ter feito a validação.

2024-06-04 15:59 UTC, erickmarx approved these changes
Está perfeito para mim, parabéns Rafa!

2024-06-04 17:41 UTC, erickmarx approved these changes

2024-06-04 22:53 UTC, natanaelsc approved these changes

2024-06-04 22:54 UTC, merged